name: ECR Image Vulnerability Scan and Update

on:
  push:
    branches:
      - main  # Trigger when code is pushed to 'main' (or you can trigger it for any push to the ECR repository)

jobs:
  scan_and_upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Pull Docker Image from ECR
        run: |
          docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Run Vulnerability Scan with Trivy
        uses: aquasecurity/trivy-action@master
        id: trivy
        with:
          image-ref: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          format: 'json'
          output: report.json

      - name: Upload Vulnerability Report to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp report.json s3://$S3_BUCKET/reports/scan_report_$(date +%F_%T).json

      - name: Check for High or Critical Vulnerabilities
        id: check_vulnerabilities
        run: |
          cat report.json | jq '.Results[].Vulnerabilities[] | select(.Severity == "HIGH" or .Severity == "CRITICAL")' > high_critical_vulnerabilities.json
          if [[ -s high_critical_vulnerabilities.json ]]; then
            echo "high_or_critical=true" >> $GITHUB_ENV
          else
            echo "high_or_critical=false" >> $GITHUB_ENV
          fi

      - name: Notify via SNS if High or Critical Vulnerabilities Exist
        if: env.high_or_critical == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws sns publish --topic-arn $SNS_TOPIC_ARN --message "High or critical vulnerabilities found in the Docker image. Please check S3 for the detailed report."

      - name: Upgrade Vulnerable Packages and Rebuild Image
        if: env.high_or_critical == 'true'
        run: |
          docker build --no-cache -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG . # Build updated image
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Run Updated Vulnerability Scan and Upload Report to S3
        if: env.high_or_critical == 'true'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          format: 'json'
          output: updated_report.json

      - name: Upload Updated Vulnerability Report to S3
        if: env.high_or_critical == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp updated_report.json s3://$S3_BUCKET/reports/updated_scan_report_$(date +%F_%T).json

      - name: Final Notification via SNS for Completed Workflow
        if: env.high_or_critical == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws sns publish --topic-arn $SNS_TOPIC_ARN --message "Docker image vulnerabilities have been addressed and an updated image has been pushed to ECR. Check S3 for the updated scan report."
